name: structure_economics_2019
channels:
  - conda-forge
dependencies:
  - python=3.7
  - r-base=3.6
  - pip
  - pip:
    - jupyter
    - metaknowledge
    - pandas
    - numpy
    - sklearn
    - umap
    - scipy
    - tqdm
    - enstop
    - seaborn
    - matplotlib
    - joblib
    - hdbscan
    - umap
    - colorcet
    - rpy2
